language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
  -  pip install -r requirements.txt --use-mirrors
  -  pip install coveralls --use-mirrors
notifications:
  slack: agiliq:4rM97fcM3RrHNA3EssNXYG3V
# command to run tests
script: 
  -  python example/manage.py test blogango.tests
  -  coverage run --omit='*migrations*' --source="." example/manage.py test blogango.tests
  
after_success:
  - coveralls  
